# Generated by Django 3.2.8 on 2021-10-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avalizacao',
            new_name='Avaliacao',
        ),
    ]
